network:
  version: 2
  ethernets: 
    ens19:
      dhcp4: no
      addresses: [10.20.20.1/24]
    ens20:
      dhcp4: no
      addresses: [10.30.30.1/24]
      nameservers:
        addresses: [10.20.20.10]
